In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("too good", 30)

[24, 4]

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[10, 5],
 [10, 22],
 [24, 4],
 [16, 2, 2],
 [18, 16, 15],
 [3, 5],
 [27, 16, 6],
 [27, 16],
 [27, 21],
 [5, 6]]

In [6]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[10,  5,  0,  0],
       [10, 22,  0,  0],
       [24,  4,  0,  0],
       [16,  2,  2,  0],
       [18, 16, 15,  0],
       [ 3,  5,  0,  0],
       [27, 16,  6,  0],
       [27, 16,  0,  0],
       [27, 21,  0,  0],
       [ 5,  6,  0,  0]])

In [10]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
X = padded_reviews
y = sentiment

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
model.fit(X, y, epochs=50, verbose=0)

In [15]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 139ms/step - loss: 0.6241 - accuracy: 1.0000


1.0

In [16]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.09535294,  0.01066562,  0.03839961, -0.08436829],
       [ 0.00447823, -0.02848549,  0.01994853, -0.00275133],
       [ 0.07786825, -0.06454674,  0.0742488 ,  0.04542086],
       [-0.04681312, -0.00769882, -0.07283767,  0.0286001 ],
       [ 0.03414384, -0.07313468,  0.00897294,  0.05861882],
       [-0.06906621, -0.02609274, -0.06534503,  0.04811746],
       [ 0.00294712,  0.06388884, -0.00894985, -0.07303545],
       [ 0.04264757, -0.00674229,  0.02338696,  0.01785721],
       [ 0.02733482,  0.01525154, -0.03562018,  0.02133377],
       [ 0.03147023,  0.03386922,  0.04337678,  0.02846028],
       [ 0.0107239 ,  0.0699845 ,  0.01699717, -0.0594316 ],
       [-0.0399818 ,  0.00536034, -0.03482826,  0.01611178],
       [-0.00447321, -0.04030913, -0.01636398, -0.0299744 ],
       [-0.04285008,  0.03432531, -0.00584088,  0.02125948],
       [ 0.04629261,  0.04035783, -0.02754606, -0.04650721],
       [-0.01623221, -0.01991068, -0.07542687,  0.04352312],
       [ 0.05767009,  0.

In [17]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [19]:
weights[10]

array([ 0.0107239 ,  0.0699845 ,  0.01699717, -0.0594316 ], dtype=float32)

In [20]:
weights[5]

array([-0.06906621, -0.02609274, -0.06534503,  0.04811746], dtype=float32)